### ISSUE TITLE
 Missing Loss Functions (Distribution Similarity and Distribution Normalizing Loss)

### ISSUE THREAD

**Issue by zy-fang** [verimsu/VCL#1]
Hi, Thank you for sharing the code. In the paper, it is mentioned that the overall loss function consists of three parts:
i) the beta-NT-Xent loss term;
ii) the Distribution Similarity Loss; and
iii) the Distribution Normalizing Loss.

However, after reviewing the code, it seems that only the first part, the NT-Xent loss term, is implemented. I couldn't find the implementation of the Distribution Similarity and Distribution Normalizing Loss components.

Could you please clarify if I have misunderstood something, or if these two loss terms are implemented elsewhere in the code?

Thank you for your help!

**Comment by ogrenenmakine** [comment]
hola... good to hear that people have attention on the code :) I was just concentrated on some other thing and this repo stayed unfinished. I have just shared the objective functions you request. Through out the week, I will share the code and the benchmarks and everything step by step.

for now the code is naive variational contrastive learning, I will share the beta-NX-ent-loss too.

But I need to test and validate the results and all... It takes time... Thanks for attention.

**Comment by zy-fang** [comment]
Got it. Thanks for your reply.

**Comment by ogrenenmakine** [comment]
hi,
I release the weights and results for 100e using naive VCL. Upcoming week, I will also share the results using beta-NT-Xent loss.
https://github.com/verimsu/VCL
